name: CI/CD

on:
  push:
    branches:
      - ci-cd

jobs:
  create-new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Initialized new tag job
        run: echo "Create new tag job initialized"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ci-cd # Especifica la rama que deseas verificar

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"


      - name: Add remote repository
        run: |
          git remote -v
          git checkout ci-cd
          git pull gitlab_runner_origin ci-cd
          chmod +x ./scripts/create_tag.sh
          if [ "$GITHUB_REF" == "refs/heads/ci-cd" ] && [ -z "$(git tag --contains $GITHUB_SHA)" ]; then ./scripts/create_tag.sh; fi
          git remote remove gitlab_runner_origin
          echo "Create new tag job finished!"
          echo "Evento que desencadenó el flujo de trabajo: $GITHUB_EVENT_NAME"
          echo "SHA de la confirmación: $GITHUB_SHA"
          echo "Rama de referencia: $GITHUB_REF" 
          echo "Nombre del repositorio: $GITHUB_REPOSITORY"
      - name: Finished new tag job
        run: echo "Create new tag job finished!"