name: CI/CD

on:
  push:
    branches:
      - ci-cd

jobs:
  create-new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Initialized new tag job
        run: echo "Create new tag job initialized"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ci-cd # Especifica la rama que deseas verificar

      - name: Set up Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"


      - name: Add remote repository
        run: |
          echo "Create new tag job finished!"
          echo "Un token de acceso: $GITHUB_TOKEN"
          echo "El nombre del repositorio: $GITHUB_REPOSITORY"
          echo "El nombre del usuario o el nombre de la acción de GitHub: $GITHUB_ACTOR"
          echo "El nombre del evento que desencadenó el flujo de trabajo: $GITHUB_EVENT_NAME"
          echo "La ruta al archivo JSON que contiene los detalles del evento que desencadenó el flujo de trabajo: $GITHUB_EVENT_PATH"
          echo "El nombre del flujo de trabajo: $GITHUB_WORKFLOW"
          echo "El nombre de la acción que se está ejecutando actualmente: $GITHUB_ACTION"
          echo "SHA de la confirmación: $GITHUB_SHA"
          echo "Rama de referencia: $GITHUB_REF" 
        
      - name: Finished new tag job
        run: echo "Create new tag job finished!"