name: CI/CD

on:
  push:
    branches:
      - ci-cd

jobs:
  create-new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Initialized new tag job
        run: echo "Create new tag job initialized"
      - name: Add remote repository
        run: |
          echo "Evento que desencadenó el flujo de trabajo: $GITHUB_EVENT_NAME"
          echo "SHA de la confirmación: $GITHUB_SHA"
          echo "Rama de referencia: $GITHUB_REF" 
          echo "Nombre del repositorio: $GITHUB_REPOSITORY"
      - name: Finished new tag job
        run: echo "Create new tag job finished!"